Repository AlaskaAirlines/auro-formkit, pull requests merged in 2025-06, with the labels that each got.

#663 Rc #658
  .github/actions/build/action.yml
  .github/actions/check-commits/action.yml
  .github/actions/surge/action.yml
  .github/actions/test/action.yml
  .github/workflows/add-project.yml
  .github/workflows/check-commits.yml
  .github/workflows/codeql.yml
  .github/workflows/pr-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/rc-check.yml
  .github/workflows/release.yml
  .github/workflows/sync-tags.yml
  .github/workflows/test-and-release.yml
  .releaserc
  components/checkbox/README.md
  components/checkbox/src/styles/auro-checkbox.scss
  components/combobox/README.md
  components/combobox/apiExamples/value.js
  components/combobox/demo/index.html
  components/combobox/docs/api.md
  components/combobox/src/auro-combobox.js
  components/combobox/test/auro-combobox.test.js
  components/counter/README.md
  components/datepicker/README.md
  components/dropdown/README.md
  components/form/README.md
  components/form/docs/api.md
  components/form/test/auro-form-interactions.test.js
  components/input/README.md
  components/menu/README.md
  components/menu/docs/api.md
  components/menu/src/auro-menu-utils.js
  components/menu/src/auro-menu.js
  components/menu/src/index.js
  components/menu/test/auro-menu.test.js
  components/radio/README.md
  components/radio/docs/api.md
  components/radio/src/auro-radio.js
  components/radio/src/styles/style.scss
  components/select/README.md
  components/select/apiExamples/inDialog.html
  components/select/apiExamples/resetState.html
  components/select/apiExamples/value.html
  components/select/apiExamples/value.js
  components/select/apiExamples/valueText.html
  components/select/apiExamples/valueText.js
  components/select/demo/api.js
  components/select/docs/api.md
  components/select/docs/partials/api.md
  components/select/src/auro-select.js
  components/select/test/auro-select.test.js
  docs/templates/bundleInstallDescription.md
Labels: semantic-status: breaking

#677 RC #676
  .github/workflows/sync-tags.yml
  .vscode/settings.json
  components/checkbox/README.md
  components/checkbox/apiExamples/basic.html
  components/checkbox/src/auro-checkbox.js
  components/checkbox/src/styles/auro-checkbox.scss
  components/checkbox/src/styles/color.scss
Labels: semantic-status: fix

#686 fix: fix dropdown padding issue with combobox
  components/dropdown/src/styles/classic/style.scss
Labels: semantic-status: fix

#685 Add layout to counter group
  components/counter/apiExamples/dropdown-snowflake.html
  components/counter/apiExamples/floaterConfig.html
  components/counter/apiExamples/onDark-dropdown-snowflake.html
  components/counter/docs/api.md
  components/counter/docs/partials/index.md
  components/counter/scripts/version.mjs
  components/counter/src/auro-counter-group.js
  components/counter/src/helptextVersion.js
  components/counter/src/styles/counter-group.scss
  components/counter/src/styles/counter-wrapper.scss
  components/counter/src/styles/shapeSize.scss
  components/counter/src/styles/tokens.scss
  components/counter/test/auro-counter-group.test.js
  components/input/docs/api.md
Labels: semantic-status: feat

#699 Fix/address counter a11y problems/#451
  components/bibtemplate/package.json
  components/bibtemplate/src/buttonVersion.js
  components/combobox/src/auro-combobox.js
  components/counter/package.json
  components/counter/src/auro-counter-group.js
  components/counter/src/auro-counter.js
  components/counter/test/auro-counter.test.js
  components/helptext/src/styles/style.scss
  components/input/package.json
  components/menu/src/auro-menu.js
  components/select/src/auro-select.js
  components/select/test/auro-select.test.js
  package-lock.json
  package.json
Labels: semantic-status: fix

#711 add `optionalLabel` slot
  components/checkbox/apiExamples/optionalLabel.html
  components/checkbox/docs/api.md
  components/checkbox/docs/partials/api.md
  components/checkbox/src/auro-checkbox-group.js
  components/combobox/apiExamples/optionalLabel.html
  components/combobox/docs/api.md
  components/combobox/docs/partials/api.md
  components/combobox/src/auro-combobox.js
  components/input/apiExamples/optionalLabel.html
  components/input/docs/api.md
  components/input/docs/partials/api.md
  components/input/src/auro-input.js
  components/input/src/base-input.js
  components/radio/docs/api.md
  components/radio/src/auro-radio-group.js
  components/select/apiExamples/optionalLabel.html
  components/select/docs/api.md
  components/select/docs/partials/api.md
  components/select/src/auro-select.js
  components/select/test/auro-select.test.js
Labels: semantic-status: feat

#720 fix: resolve bugs when programmatically setting value on combobox
  components/combobox/docs/api.md
  components/combobox/src/auro-combobox.js
Labels: semantic-status: fix
