Repository AlaskaAirlines/auro-formkit, pull requests merged in 2025-05, with the labels that each got.

#392 docs(form): more in-depth form docs
  components/form/apiExamples/column-layout.html
  components/form/apiExamples/complex.html
  components/form/demo/index.html
  components/form/demo/registerDemoDeps.js
  components/form/docs/partials/index.md
Labels: Type: Documentation, DEV

#590 fix: set unique id and arialabel correctly in input/radio/checkbox #589
  components/checkbox/docs/api.md
  components/checkbox/src/auro-checkbox.js
  components/checkbox/test/auro-checkbox.test.js
  components/input/docs/api.md
  components/input/src/auro-input.js
  components/input/src/base-input.js
  components/input/test/auro-input.test.js
  components/radio/docs/api.md
  components/radio/src/auro-radio.js
  components/radio/test/auro-radio.test.js
Labels: DEV

#607 fix: update check for hasValue to accommodate array value types
  packages/form-validation/src/validation.js
Labels: MAIN

#629 Github actions sync tags workflow
  .github/workflows/sync-tags.yml
Labels: semantic-status: chore

#630 Rc #627
  .github/workflows/add-project.yml
  .github/workflows/check-commits.yml
  .github/workflows/codeql.yml
  .github/workflows/pr-release.yml
  .github/workflows/sync-tags.yml
  .github/workflows/test-and-release.yml
  .github/workflows/testPublish.yml
  .releaserc
  CHANGELOG.md
  components/checkbox/docs/api.md
  components/checkbox/src/auro-checkbox.js
  components/checkbox/test/auro-checkbox.test.js
  components/combobox/src/auro-combobox.js
  components/form/apiExamples/column-layout.html
  components/form/apiExamples/complex.html
  components/form/demo/index.html
  components/form/demo/registerDemoDeps.js
  components/form/docs/partials/index.md
  components/form/src/auro-form.js
  components/input/docs/api.md
  components/input/src/auro-input.js
  components/input/src/base-input.js
  components/input/test/auro-input.test.js
  components/menu/src/auro-menu.js
  components/radio/docs/api.md
  components/radio/src/auro-radio.js
  components/radio/test/auro-radio.test.js
  components/select/apiExamples/autocomplete.html
  components/select/demo/api.html
  components/select/demo/index.html
  components/select/docs/api.md
  components/select/docs/partials/api.md
  components/select/docs/partials/index.md
  components/select/src/auro-select.js
  components/select/src/styles/style.scss
  components/select/test/auro-select.test.js
  package.json
  packages/config/src/internal.rollup.config.mjs
Labels: released on @rc, semantic-status: feat
