Repository AlaskaAirlines/auro-formkit, pull requests merged in 2025-07, with the labels that each got.

#769 Datepicker bugs round 1
  components/datepicker/src/auro-datepicker.js
  components/datepicker/src/styles/snowflake/style.scss
  components/datepicker/src/styles/style.scss
Labels: semantic-status: fix

#739 tokenize hardcode sizing values
  components/counter/src/styles/counter-group.scss
  components/input/src/styles/classic/style.scss
  components/input/src/styles/emphasized/style.scss
  components/input/src/styles/snowflake/style.scss
  components/menu/src/styles/default/style-menuoption.scss
  components/select/src/styles/style.scss
Labels: semantic-status: refactor

#776 Add npm script local-demo to make shareable demos
  .gitignore
  local-demo.sh
  package.json
Labels: semantic-status: chore

#773 fix: notify value change properly on input's value change #683
  components/input/src/base-input.js
Labels: semantic-status: fix

#750 test: add test on setting `value`
  components/form/package.json
  components/form/test/auro-form-interactions.test.js
  components/form/test/auro-form.test.js
  components/form/test/validation-value-setting.test.js
Labels: semantic-status: test

#783 fix: add `aria-disabled` attribute on disabled counter #774
  components/counter/src/auro-counter.js
  components/counter/test/auro-counter-group.test.js
  components/counter/test/auro-counter.test.js
Labels: semantic-status: fix

#815 fix: menuoption inherit shape and size from parent's attributes
  components/menu/src/auro-menuoption.js
Labels: semantic-status: fix

#816 fix: set to default menu shape and size when bib is fullscreen in combobox and select
  components/bibtemplate/src/auro-bibtemplate.js
  components/bibtemplate/src/styles/style.scss
  components/combobox/src/auro-combobox.js
  components/combobox/src/styles/style.scss
  components/select/src/auro-select.js
Labels: semantic-status: fix

#835 fix: remove menuoption-border bleeding
  components/menu/src/styles/default/color-menuoption.scss
Labels: semantic-status: fix

#841 set disabled text color on disabled input
  components/input/src/styles/color.scss
Labels: semantic-status: fix

#846 fix: hide datepicker's clear when it's not holding focus/hover #843
  components/datepicker/src/styles/style.scss
Labels: semantic-status: fix

#847 Update logic around type classes used for input layout
  components/input/src/auro-input.js
Labels: semantic-status: feat

#987 fix: force rerender snowflake/emphasized input when it gets focus #891
  components/input/src/styles/emphasized/style.scss
  components/input/src/styles/snowflake/style.scss
Labels: semantic-status: fix

#988 fix: update display property on native select #863
  components/select/src/auro-select.js
Labels: semantic-status: fix

#989 fix: update ondark error color to match to the figma spec #955
  components/counter/src/styles/tokens.scss
  components/datepicker/src/styles/tokens.scss
  components/dropdown/src/styles/color.scss
  components/helptext/src/styles/color.scss
  components/input/src/styles/classic/color.scss
  components/input/src/styles/color.scss
  components/input/src/styles/default/color.scss
  components/input/src/styles/tokens.scss
  components/select/src/styles/style.scss
  components/select/src/styles/tokens.scss
Labels: semantic-status: fix

#998 fix: center-align trigger and helpText for snowflake dropdown #957
  components/datepicker/src/styles/snowflake/style.scss
  components/dropdown/src/styles/color.scss
  components/dropdown/src/styles/snowflake/style.scss
Labels: semantic-status: fix

#1001 ci: move auro-libary from dep to devDep
  components/bibtemplate/src/iconVersion.js
  components/counter/src/iconVersion.js
  components/datepicker/package.json
  components/menu/src/iconVersion.js
  package-lock.json
  package.json
  packages/build-tools/src/postinstall.mjs
Labels: semantic-status: ci

#1005 Add missing body-default to select snowflake value
  components/select/src/auro-select.js
Labels: semantic-status: fix

#1010 RC #1009
  components/checkbox/src/styles/auro-checkbox.scss
  components/combobox/src/auro-combobox.js
  components/combobox/src/styles/style.scss
  components/combobox/test/auro-combobox.test.js
  components/counter/src/styles/counter-group.scss
  components/counter/src/styles/style.scss
  components/dropdown/src/auro-dropdown.js
  components/dropdown/src/styles/style.scss
  components/dropdown/test/auro-dropdown.test.js
  components/input/src/styles/default/style.scss
  components/select/src/styles/style.scss
Labels: semantic-status: feat

#1013 try catch DOMParser
  components/bibtemplate/package.json
  components/counter/package.json
  components/datepicker/package.json
  components/dropdown/package.json
  components/input/package.json
  components/menu/package.json
  package-lock.json
  packages/utils/src/iconUtil.js
Labels: semantic-status: fix

#1015 RC #1014
  components/bibtemplate/package.json
  components/counter/package.json
  components/datepicker/package.json
  components/dropdown/package.json
  components/input/package.json
  components/menu/package.json
  package-lock.json
  packages/utils/src/iconUtil.js
Labels: semantic-status: fix
